steps:
  - id: build-backend
    name: "docker"
    args:
      - build
      - --file=Dockerfile
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .
    dir: "backend"
  - id: push-backend
    name: "docker"
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    dir: "backend"
    waitFor: ["build-backend"]
  - id: "apply-migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - "-c"
      - "/buildstep/execute.sh -i $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA -e DATABASE_URL=$$DATABASE_URL -s $_CLOUDSQL_INSTANCE_FULL_NAME -- yarn prisma migrate deploy"
    secretEnv: ["DATABASE_URL"]
    dir: "backend"
    waitFor: ["push-backend"]
  - id: deploy-backend
    name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - training-backend2
      - --quiet
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --service-account=$_SERVICE_ACCOUNT
      - --add-cloudsql-instances=$_CLOUDSQL_INSTANCE_FULL_NAME
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --concurrency=40
      - --cpu=1
      - --memory=512Mi
      - --max-instances=3
      - --min-instances=0
      - --no-use-http2
      - --allow-unauthenticated
      - --no-cpu-throttling
      - --ingress=all
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID
      - --update-secrets=DATABASE_URL=BLOG_TRAINING_DATABASE_URL:latest
    dir: "backend"
    waitFor: ["apply-migrations"]
timeout: 2000s
substitutions:
  _REGION: us-central1
  _CLOUDSQL_INSTANCE_FULL_NAME: my-demo-project-20210227:us-central1:blog-tutorial-db
  _ARTIFACT_REPOSITORY_IMAGE_NAME: us-central1-docker.pkg.dev/my-demo-project-20210227/blog-training-backend-app/blog-backend
  _SERVICE_ACCOUNT: by-terraform@my-demo-project-20210227.iam.gserviceaccount.com	
  # _CONTENTS_BUCKET_NAME: by-terraform
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/BLOG_TRAINING_DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/REGION/versions/latest
      env: REGION
    - versionName: projects/$PROJECT_ID/secrets/CLOUDSQL_INSTANCE_FULL_NAME/versions/latest
      env: CLOUDSQL_INSTANCE_FULL_NAME
    - versionName: projects/$PROJECT_ID/secrets/ARTIFACT_REPOSITORY_IMAGE_NAME/versions/latest
      env: ARTIFACT_REPOSITORY_IMAGE_NAME
    - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT/versions/latest
      env: SERVICE_ACCOUNT

# ビルド結果に生成したイメージ情報を表示する
# https://cloud.google.com/build/docs/building/build-containers
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA